/**
 * Node.js script to generate PWA icons
 * Requires: canvas package (npm install canvas)
 * 
 * Run: node generate-icons.js
 */

// This script requires the 'canvas' package
// Install with: npm install canvas
// 
// Alternative: Use the HTML generator (icon-generator.html) in a browser

const fs = require('fs');
const path = require('path');

// Simple SVG-based icon generator (doesn't require canvas)
function generateIconSVG(size) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#6366f1;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#8b5cf6;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="${size}" height="${size}" fill="url(#grad)"/>
  <circle cx="${size * 0.35}" cy="${size * 0.5}" r="${size * 0.12}" fill="#ffffff"/>
  <circle cx="${size * 0.65}" cy="${size * 0.5}" r="${size * 0.12}" fill="#ffffff"/>
  <rect x="${size * 0.35}" y="${size * 0.44}" width="${size * 0.3}" height="${size * 0.12}" fill="#ffffff"/>
</svg>`;
}

// Note: This generates SVG files. For PNG, use:
// 1. The HTML generator (icon-generator.html) in a browser
// 2. Online SVG to PNG converter
// 3. Install canvas package and use it to convert SVG to PNG

console.log('Icon Generator');
console.log('==============');
console.log('');
console.log('For best results, use the HTML generator (icon-generator.html) in your browser.');
console.log('It will generate proper PNG files that you can download.');
console.log('');
console.log('Alternatively, you can:');
console.log('1. Use an online tool like https://realfavicongenerator.net/');
console.log('2. Create icons manually using image editing software');
console.log('3. Use the SVG files generated by this script and convert them to PNG');
console.log('');

// Generate SVG files as fallback
try {
    const icon192SVG = generateIconSVG(192);
    const icon512SVG = generateIconSVG(512);
    
    fs.writeFileSync(path.join(__dirname, 'icon-192.svg'), icon192SVG);
    fs.writeFileSync(path.join(__dirname, 'icon-512.svg'), icon512SVG);
    
    console.log('✓ Generated icon-192.svg');
    console.log('✓ Generated icon-512.svg');
    console.log('');
    console.log('Note: Convert these SVG files to PNG for PWA use.');
    console.log('You can use an online converter or image editing software.');
} catch (error) {
    console.log('Error generating SVG files:', error.message);
    console.log('Please use the HTML generator instead.');
}

